spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/user_db
    username: myuser
    password: mypassword

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: false